apiVersion: v1
data:
  DEV_APP_USER: devuser
  EXPIRATION_MINUTES: "30"
  GOMAXPROCS: "2"
  JWT_ALGORITHM: HS256
  S3_DEFAULT_BUCKET: devtest
  S3_ENDPOINT: minio.trahan.dev
  S3_KEYID: biCYCcKXjnOpGBG5biue
  S3_USESSL: "true"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"DEV_APP_USER":"devuser","EXPIRATION_MINUTES":"30","GOMAXPROCS":"2","JWT_ALGORITHM":"HS256","S3_DEFAULT_BUCKET":"devtest","S3_ENDPOINT":"minio.trahan.dev","S3_KEYID":"biCYCcKXjnOpGBG5biue","S3_USESSL":"true"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2025-04-08T01:44:10Z","name":"goapp-configmap","namespace":"development","resourceVersion":"26175623","uid":"13c97748-cbc0-4236-935c-d5c8d668fede"}}
  creationTimestamp: "2025-04-08T01:44:10Z"
  name: goapp-configmap
  namespace: development
  resourceVersion: "26177935"
  uid: 13c97748-cbc0-4236-935c-d5c8d668fede
