apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: smbplusplus-cluster-dev
  namespace: development
spec:
  instances: 3
  bootstrap:
    initdb:
      database: s2user
      owner: s2user
      secret:
        name: s2-cnpg-secret
  storage:
    size: 4Gi
  postgresql:
    pg_hba:
      - host all all all scram-sha-256
  monitoring:
    enablePodMonitor: true
