#!/bin/bash
source .env
export GOOSE_DBSTRING GOOSE_MIGRATION_DIR GOOSE_DRIVER DATABASE_URL CF_TOKEN DEV_APP_USER_PW 
export EXPIRATION_MINUTES JWT_ALGORITHM JWT_KEY S3_ENDPOINT S3_KEYID S3_SECRET S3_DEFAULT_BUCKET S3_USESSL DEV_APP_USER DEV_APP_PASS